export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function ContactLayout({ children }) {
  return (
    <div className="relative">
      {children}
    </div>
  )
}
